main:
  data-source: https://raw.githubusercontent.com/ALMIGHTYABE/Pixel-Pirate-Tracker/main/ppmain.csv

sales:
  api: https://api.paintswap.finance/v2/sales?collections=0x2aa5d15eb36e5960d056e8fea6e7bb3e2a06a351&numToFetch=1000
  history: https://raw.githubusercontent.com/ALMIGHTYABE/Pixel-Pirate-Tracker/main/pphistory.csv

stats:
  api: https://api.paintswap.finance/v2/collections/0x2aa5d15eb36e5960d056e8fea6e7bb3e2a06a351

treasure:
  data: https://raw.githubusercontent.com/ALMIGHTYABE/Pixel-Pirate-Tracker/main/Snapshot%20Data/Treasure%20Address%20Wise.csv
